=== SimoneGiordanoIT/Unofficial-Forum-SpazioGaming/PAGINE SITO/SCHEMI/AreeInteresse.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="aree_int">
   <xsd:complexType> 
      <xsd:sequence>
	 <xsd:element ref="gioco" maxOccurs="unbounded" />
      </xsd:sequence>
   </xsd:complexType>
</xsd:element>

<xsd:element name="gioco">
   <xsd:complexType>
      <xsd:sequence>
         <xsd:element ref="ID" />
         <xsd:element ref="nome" />
         <xsd:element ref="tag" />
         <xsd:element ref="flag_attivo" />
      </xsd:sequence>
   </xsd:complexType>
</xsd:element>

<xsd:element name="ID" type="xsd:int" />

<xsd:element name="nome" type="xsd:string" />

<xsd:element name="tag" type="xsd:string"/>

<xsd:element name="flag_attivo" type="xsd:boolean"/>


</xsd:schema>

=== SimoneGiordanoIT/Unofficial-Forum-SpazioGaming/PAGINE SITO/SCHEMI/AreeInteresse.xml
<?xml version="1.0" encoding="UTF-8"?>
<aree_int xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AreeInteresse.xsd"><gioco><ID>1</ID><nome>League of Legends</nome><tag>LOL</tag><flag_attivo>1</flag_attivo></gioco><gioco><ID>2</ID><nome>Call Of Duty</nome><tag>COD</tag><flag_attivo>1</flag_attivo></gioco></aree_int>
