=== SimoneGiordanoIT/Unofficial-Forum-SpazioGaming/PAGINE SITO/SCHEMI/commenti.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="reputazioneC">
   <xsd:complexType> 
      <xsd:sequence>
	 <xsd:element ref="linker" maxOccurs="unbounded" />
      </xsd:sequence>
   </xsd:complexType>
</xsd:element>

<xsd:element name="linker">
   <xsd:complexType>
      <xsd:sequence>
         <xsd:element ref="ID_creatore" />
         <xsd:element ref="ID_post" />
         <xsd:element ref="ID_comm" />
         <xsd:element ref="voto" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
   </xsd:complexType>
</xsd:element>

<xsd:element name="ID_creatore" type="xsd:int" />

<xsd:element name="ID_post" type="xsd:int" />

<xsd:element name="ID_comm" type="xsd:int" />

<xsd:element name="voto" type="vote" />

<xsd:complexType name="vote">
  <xsd:sequence>
    <xsd:element name="votoDato" type="xsd:int" />
    <xsd:element name="ID_votante" type="xsd:int"/>
  </xsd:sequence>
</xsd:complexType>

<xsd:element name="votoDato" type="xsd:int" />
<xsd:element name="ID_votante" type="xsd:int" />



</xsd:schema>

=== SimoneGiordanoIT/Unofficial-Forum-SpazioGaming/PAGINE SITO/SCHEMI/commenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<reputazioneC xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="commenti.xsd"><linker><ID_creatore>2</ID_creatore><ID_post>1</ID_post><ID_comm>1</ID_comm><voto><votoDato>3</votoDato><ID_votante>4</ID_votante></voto><voto><votoDato>5</votoDato><ID_votante>4</ID_votante></voto><voto><votoDato>1</votoDato><ID_votante>4</ID_votante></voto><voto><votoDato>5</votoDato><ID_votante>4</ID_votante></voto></linker><linker><ID_creatore>3</ID_creatore><ID_post>1</ID_post><ID_comm>2</ID_comm><voto><votoDato>3</votoDato><ID_votante>4</ID_votante></voto></linker><linker><ID_creatore>3</ID_creatore><ID_post>1</ID_post><ID_comm>3</ID_comm></linker><linker><ID_creatore>2</ID_creatore><ID_post>1</ID_post><ID_comm>4</ID_comm></linker><linker><ID_creatore>3</ID_creatore><ID_post>1</ID_post><ID_comm>5</ID_comm></linker><linker><ID_creatore>2</ID_creatore><ID_post>1</ID_post><ID_comm>6</ID_comm><voto><votoDato>1</votoDato><ID_votante>3</ID_votante></voto><voto><votoDato>1</votoDato><ID_votante>4</ID_votante></voto><voto><votoDato>1</votoDato><ID_votante>4</ID_votante></voto></linker><linker><ID_creatore>3</ID_creatore><ID_post>3</ID_post><ID_comm>1</ID_comm><voto><votoDato>3</votoDato><ID_votante>4</ID_votante></voto></linker><linker><ID_creatore>1</ID_creatore><ID_post>3</ID_post><ID_comm>2</ID_comm><voto><votoDato>4</votoDato><ID_votante>3</ID_votante></voto></linker><linker><ID_creatore>3</ID_creatore><ID_post>7</ID_post><ID_comm>1</ID_comm><voto><votoDato>5</votoDato><ID_votante>4</ID_votante></voto><voto><votoDato>1</votoDato><ID_votante>4</ID_votante></voto></linker></reputazioneC>
