=== SimoneGiordanoIT/Unofficial-Forum-SpazioGaming/PAGINE SITO/SCHEMI/gestionePref.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="elenco_preferiti">
   <xsd:complexType> 
      <xsd:sequence>
	 <xsd:element ref="preferiti" maxOccurs="unbounded" />
      </xsd:sequence>
   </xsd:complexType>
</xsd:element>

<xsd:element name="preferiti">
   <xsd:complexType>
      <xsd:sequence>
         <xsd:element ref="ID_UT" />
         <xsd:element ref="ID_Area" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
   </xsd:complexType>
</xsd:element>

<xsd:element name="ID_UT" type="xsd:int" />

<xsd:element name="ID_Area" type="xsd:int" />

</xsd:schema>

=== SimoneGiordanoIT/Unofficial-Forum-SpazioGaming/PAGINE SITO/SCHEMI/gestionePref.xml
<?xml version="1.0" encoding="UTF-8"?>
<elenco_preferiti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gestionePref.xsd"><preferiti><ID_UT>1</ID_UT></preferiti><preferiti><ID_UT>2</ID_UT><ID_Area>1</ID_Area></preferiti><preferiti><ID_UT>3</ID_UT></preferiti><preferiti><ID_UT>4</ID_UT><ID_Area>1</ID_Area></preferiti><preferiti><ID_UT>5</ID_UT></preferiti></elenco_preferiti>
