=== SimoneGiordanoIT/Unofficial-Forum-SpazioGaming/PAGINE SITO/SCHEMI/gestioneMessaggiModeraPost.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="elenco_mex">
   <xsd:complexType> 
      <xsd:sequence>
	 <xsd:element ref="mex" maxOccurs="unbounded" />
      </xsd:sequence>
   </xsd:complexType>
</xsd:element>

<xsd:element name="mex">
   <xsd:complexType>
      <xsd:sequence>
         <xsd:element ref="ID_UT" />
         <xsd:element ref="ID_MOD" />
         <xsd:element ref="ID_POST" />
         <xsd:element ref="testoMess" />
         <xsd:element ref="flag_lett" />
      </xsd:sequence>
   </xsd:complexType>
</xsd:element>

<xsd:element name="ID_UT" type="xsd:int" />

<xsd:element name="ID_MOD" type="xsd:int" />

<xsd:element name="ID_POST" type="xsd:int" />

<xsd:element name="testoMess" type="xsd:string"/>

<xsd:element name="flag_lett" type="xsd:boolean"/>


</xsd:schema>

=== SimoneGiordanoIT/Unofficial-Forum-SpazioGaming/PAGINE SITO/SCHEMI/gestioneMessaggiModeraPost.xml
<?xml version="1.0" encoding="UTF-8"?>
<elenco_mex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gestioneMessaggiModeraPost.xsd">
  <mex>
    <ID_UT>4</ID_UT>
    <ID_MOD>3</ID_MOD>
    <ID_POST>1</ID_POST>
    <testoMess>il testo del primo post non va bene</testoMess>
    <flag_lett>0</flag_lett>
  </mex>
  <mex>
    <ID_UT>4</ID_UT>
    <ID_MOD>3</ID_MOD>
    <ID_POST>2</ID_POST>
    <testoMess>il testo del SECONDO post non va bene</testoMess>
    <flag_lett>0</flag_lett>
  </mex>
  <mex>
    <ID_UT>4</ID_UT>
    <ID_MOD>2</ID_MOD>
    <ID_POST>7</ID_POST>
    <testoMess>NON VA BENE,CAMBIALO</testoMess>
    <flag_lett>1</flag_lett>
  </mex>
</elenco_mex>
