=== SimoneGiordanoIT/Unofficial-Forum-SpazioGaming/PAGINE SITO/SCHEMI/gestioneMessaggiCreaArea.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="elenco_messaggi">
   <xsd:complexType> 
      <xsd:sequence>
	 <xsd:element ref="messaggio" maxOccurs="unbounded" />
      </xsd:sequence>
   </xsd:complexType>
</xsd:element>

<xsd:element name="messaggio">
   <xsd:complexType>
      <xsd:sequence>
         <xsd:element ref="ID_UT" />
         <xsd:element ref="flag_sender" />
         <xsd:element ref="testoMess" />
         <xsd:element ref="flag_lettura" />
      </xsd:sequence>
   </xsd:complexType>
</xsd:element>

<xsd:element name="ID_UT" type="xsd:int" />

<xsd:element name="flag_sender" type="xsd:boolean"/>

<xsd:element name="testoMess" type="xsd:string"/>

<xsd:element name="flag_lettura" type="xsd:boolean"/>


</xsd:schema>

=== SimoneGiordanoIT/Unofficial-Forum-SpazioGaming/PAGINE SITO/SCHEMI/gestioneMessaggiCreaArea.xml
<?xml version="1.0" encoding="UTF-8"?>
<elenco_messaggi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gestioneMessaggiCreaArea.xsd"><messaggio><ID_UT>4</ID_UT><flag_sender>0</flag_sender><testoMess>Vorrei che aggiungesse Battflefield come gioco</testoMess><flag_lettura>0</flag_lettura></messaggio><messaggio><ID_UT>4</ID_UT><flag_sender>0</flag_sender><testoMess>vorrei bannare tizio</testoMess><flag_lettura>0</flag_lettura></messaggio><messaggio><ID_UT>4</ID_UT><flag_sender>1</flag_sender><testoMess>va bene</testoMess><flag_lettura>0</flag_lettura></messaggio></elenco_messaggi>
